@echo off
echo Stopping node.exe...
C:\Windows\System32\taskkill.exe /F /IM node.exe /T >nul 2>&1
echo Waiting 2 seconds...
C:\Windows\System32\timeout.exe /t 2 /nobreak >nul
echo Starting server hidden...
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -File start_server_hidden.ps1
echo Done!
